export default {
  LOGGED_IN: 'LOGGED_IN',
  LOGIN_IN_PROGRESS: 'LOGIN_IN_PROGRESS',

  SIGNOUT_IN_PROGRESS: 'SIGNOUT_IN_PROGRESS',
  SIGNED_OUT: 'SIGNED_OUT',

  DRIVERS_LOADED: 'DRIVERS_LOADED',

  LOADING: 'LOADING',
  ERROR: 'ERROR'
};
