export default {
  LOGGED_IN: 'LOGGED_IN',
  LOGIN_IN_PROGRESS: 'LOGIN_IN_PROGRESS',

  TOTAL_TIME_TO_SPEND: 5,

  DRIVERS_LOADED: 'DRIVERS_LOADED',
  DRIVER_LOADED: 'DRIVER_LOADED',
  DRIVER_SELECTED: 'DRIVER_SELECTED',

  ADD_PASSENGER_INFO: 'ADD_PASSENGER_INFO',

  PACKAGES_LOADED: 'PACKAGES_LOADED',

  DESTINATIONS_LOADED: 'DESTINATIONS_LOADED',
  DESTINATION_ADDED: 'DESTINATION_ADDED',
  DESTINATION_REMOVED: 'DESTINATION_REMOVED',

  ADD_PACKAGE: 'ADD_PACKAGE',
  PASSENGER_INFO: 'PASSENGER_INFO',
  CHECK_VALIDATION: 'CHECK_VALIDATION',

  LOADING: 'LOADING',
  ERROR: 'ERROR'
};
