export default {
  LOGGED_IN: 'LOGGED_IN',
  LOGIN_IN_PROGRESS: 'LOGIN_IN_PROGRESS',

  DRIVERS_LOADED: 'DRIVERS_LOADED',
  DRIVER_LOADED: 'DRIVER_LOADED',

  PACKAGES_LOADED: 'PACKAGES_LOADED',

  DESTINATIONS_LOADED: 'DESTINATIONS_LOADED',
  DESTINATION_ADDED: 'DESTINATION_ADDED',
  ADD_PACKAGE: 'ADD_PACKAGE',

  LOADING: 'LOADING',
  ERROR: 'ERROR'
};
